/**
 * Dynamic Pricing Engine & Mapping Store
 * Supports real-time price overrides configured by the Admin.
 */

export interface PricingItem {
  id: string;
  name: string;
  category: "sms" | "country" | "smm";
  icon?: string;
  code?: string;
  wholesaleUSD: number;
  wholesaleEstNGN: number; // estimated using ~₦1,600 / $1
  retailNGN: number;
  active: boolean;
  unitLabel?: string; // e.g. "per number", "per 1,000 followers"
}

export const DEFAULT_PRICING: PricingItem[] = [
  // --- Virtual Numbers Target Services ---
  {
    id: "sms_whatsapp",
    name: "WhatsApp",
    category: "sms",
    icon: "🟢",
    wholesaleUSD: 0.20,
    wholesaleEstNGN: 320,
    retailNGN: 850,
    active: true,
    unitLabel: "per number",
  },
  {
    id: "sms_telegram",
    name: "Telegram",
    category: "sms",
    icon: "✈️",
    wholesaleUSD: 0.15,
    wholesaleEstNGN: 240,
    retailNGN: 750,
    active: true,
    unitLabel: "per number",
  },
  {
    id: "sms_googlevoice",
    name: "Google Voice",
    category: "sms",
    icon: "📞",
    wholesaleUSD: 0.55,
    wholesaleEstNGN: 880,
    retailNGN: 1800,
    active: true,
    unitLabel: "per number",
  },
  {
    id: "sms_signal",
    name: "Signal Messenger",
    category: "sms",
    icon: "💬",
    wholesaleUSD: 0.20,
    wholesaleEstNGN: 320,
    retailNGN: 850,
    active: true,
    unitLabel: "per number",
  },
  {
    id: "sms_openai",
    name: "OpenAI / ChatGPT",
    category: "sms",
    icon: "🤖",
    wholesaleUSD: 0.25,
    wholesaleEstNGN: 400,
    retailNGN: 950,
    active: true,
    unitLabel: "per number",
  },
  {
    id: "sms_google",
    name: "Google / Gmail",
    category: "sms",
    icon: "🔴",
    wholesaleUSD: 0.25,
    wholesaleEstNGN: 400,
    retailNGN: 900,
    active: true,
    unitLabel: "per number",
  },
  {
    id: "sms_tinder",
    name: "Tinder",
    category: "sms",
    icon: "🔥",
    wholesaleUSD: 0.30,
    wholesaleEstNGN: 480,
    retailNGN: 1200,
    active: true,
    unitLabel: "per number",
  },
  {
    id: "sms_tiktok",
    name: "TikTok",
    category: "sms",
    icon: "🎵",
    wholesaleUSD: 0.20,
    wholesaleEstNGN: 320,
    retailNGN: 800,
    active: true,
    unitLabel: "per number",
  },
  {
    id: "sms_facebook",
    name: "Facebook",
    category: "sms",
    icon: "📘",
    wholesaleUSD: 0.20,
    wholesaleEstNGN: 320,
    retailNGN: 850,
    active: true,
    unitLabel: "per number",
  },
  {
    id: "sms_twitter",
    name: "Twitter / X",
    category: "sms",
    icon: "🐦",
    wholesaleUSD: 0.20,
    wholesaleEstNGN: 320,
    retailNGN: 850,
    active: true,
    unitLabel: "per number",
  },

  // --- Virtual Numbers Country Routing ---
  {
    id: "country_us",
    name: "United States (+1)",
    category: "country",
    code: "+1",
    wholesaleUSD: 0.55,
    wholesaleEstNGN: 880,
    retailNGN: 1200,
    active: true,
    unitLabel: "base rate",
  },
  {
    id: "country_ng",
    name: "Nigeria (+234)",
    category: "country",
    code: "+234",
    wholesaleUSD: 0.25,
    wholesaleEstNGN: 400,
    retailNGN: 850,
    active: true,
    unitLabel: "base rate",
  },
  {
    id: "country_gb",
    name: "United Kingdom (+44)",
    category: "country",
    code: "+44",
    wholesaleUSD: 0.60,
    wholesaleEstNGN: 960,
    retailNGN: 1500,
    active: true,
    unitLabel: "base rate",
  },
  {
    id: "country_gh",
    name: "Ghana (+233)",
    category: "country",
    code: "+233",
    wholesaleUSD: 0.35,
    wholesaleEstNGN: 560,
    retailNGN: 950,
    active: true,
    unitLabel: "base rate",
  },
  {
    id: "country_za",
    name: "South Africa (+27)",
    category: "country",
    code: "+27",
    wholesaleUSD: 0.40,
    wholesaleEstNGN: 640,
    retailNGN: 1100,
    active: true,
    unitLabel: "base rate",
  },
  {
    id: "country_ke",
    name: "Kenya (+254)",
    category: "country",
    code: "+254",
    wholesaleUSD: 0.30,
    wholesaleEstNGN: 480,
    retailNGN: 900,
    active: true,
    unitLabel: "base rate",
  },

  // --- SMM Boosting Services (JAP) ---
  {
    id: "smm_9011",
    name: "Twitter / X Followers (7D Refill)",
    category: "smm",
    icon: "🐦",
    wholesaleUSD: 0.375,
    wholesaleEstNGN: 600,
    retailNGN: 3500,
    active: true,
    unitLabel: "per 1,000",
  },
  {
    id: "smm_10452",
    name: "Instagram High-Quality Followers (Non-Drop)",
    category: "smm",
    icon: "📸",
    wholesaleUSD: 0.85,
    wholesaleEstNGN: 1360,
    retailNGN: 4500,
    active: true,
    unitLabel: "per 1,000",
  },
  {
    id: "smm_8120",
    name: "Instagram Instant High-Speed Likes",
    category: "smm",
    icon: "❤️",
    wholesaleUSD: 0.12,
    wholesaleEstNGN: 192,
    retailNGN: 1500,
    active: true,
    unitLabel: "per 1,000",
  },
  {
    id: "smm_7421",
    name: "TikTok Video Views (Algorithm Booster)",
    category: "smm",
    icon: "🎵",
    wholesaleUSD: 0.02,
    wholesaleEstNGN: 32,
    retailNGN: 800,
    active: true,
    unitLabel: "per 1,000",
  },
  {
    id: "smm_6205",
    name: "Telegram Channel / Group Members",
    category: "smm",
    icon: "✈️",
    wholesaleUSD: 0.80,
    wholesaleEstNGN: 1280,
    retailNGN: 4000,
    active: true,
    unitLabel: "per 1,000",
  },
];
