/**
 * JustAnotherPanel (JAP) SMM API Provider Client
 * Implements the standard SMM API v2 specification.
 */

const JAP_API_URL = process.env.JAP_API_URL || "https://justanotherpanel.com/api/v2";

export interface SmmServiceConfig {
  id: string;
  japServiceId: number;
  category: 
    | "Twitter" 
    | "Instagram" 
    | "TikTok" 
    | "Telegram" 
    | "YouTube" 
    | "Facebook" 
    | "Spotify"
    | "Snapchat"
    | "Threads"
    | "Discord"
    | "LinkedIn"
    | "Audiomack"
    | "Twitch"
    | "Kick"
    | "Pinterest";
  name: string;
  description: string;
  wholesaleCostUSD: number;
  retailPriceNGN: number;
  minQuantity: number;
  maxQuantity: number;
  speed: string;
  guarantee: string;
}

// Hand-picked curated services catalog with high profit margins across all platforms
export const CURATED_SMM_CATALOG: SmmServiceConfig[] = [
  // --- Instagram ---
  {
    id: "ig-fol-fast",
    japServiceId: 2830,
    category: "Instagram",
    name: "Instagram Followers [Super Fast 50k/Day | 90 Days Auto-Refill]",
    description: "High quality stable followers with 90-day refill guarantee.",
    wholesaleCostUSD: 0.25,
    retailPriceNGN: 3850,
    minQuantity: 100,
    maxQuantity: 500000,
    speed: "50,000 / Day",
    guarantee: "90 Days Refill",
  },
  {
    id: "ig-fol-nigerian",
    japServiceId: 10214,
    category: "Instagram",
    name: "Instagram Followers [100% Real Active Nigerian Profiles | Organic Growth]",
    description: "Real organic Nigerian accounts with local posts and profile photos.",
    wholesaleCostUSD: 0.75,
    retailPriceNGN: 6800,
    minQuantity: 50,
    maxQuantity: 20000,
    speed: "5,000 / Day",
    guarantee: "100% Organic",
  },
  {
    id: "ig-fol-guaranteed",
    japServiceId: 1413,
    category: "Instagram",
    name: "Instagram Followers [Non-Drop Auto-Refill | 365 Days Lifetime Guarantee | Real HQ]",
    description: "Zero drop lifetime guaranteed followers. Beats competitor ₦19k-₦27k rates.",
    wholesaleCostUSD: 1.80,
    retailPriceNGN: 14500,
    minQuantity: 100,
    maxQuantity: 500000,
    speed: "3,000 / Day",
    guarantee: "365 Days Lifetime",
  },
  {
    id: "ig-lik-hq",
    japServiceId: 2831,
    category: "Instagram",
    name: "Instagram HQ Likes [Instant 0-5m | Non-Drop Real Profiles]",
    description: "Fast start likes on any post, reel, or IGTV.",
    wholesaleCostUSD: 0.08,
    retailPriceNGN: 550,
    minQuantity: 50,
    maxQuantity: 100000,
    speed: "100,000 / Day",
    guarantee: "Non-Drop",
  },
  {
    id: "ig-viw-reels",
    japServiceId: 8155,
    category: "Instagram",
    name: "Instagram Reel & Video Views [Algorithm FYP Booster | High Reach]",
    description: "Instant video views with explore and algorithm trigger.",
    wholesaleCostUSD: 0.03,
    retailPriceNGN: 350,
    minQuantity: 500,
    maxQuantity: 1000000,
    speed: "500,000 / Day",
    guarantee: "Guaranteed",
  },
  {
    id: "ig-com-custom",
    japServiceId: 8190,
    category: "Instagram",
    name: "Instagram Custom Comments [Targeted Active Profiles | Custom Text]",
    description: "Custom written comments from active accounts.",
    wholesaleCostUSD: 0.75,
    retailPriceNGN: 5800,
    minQuantity: 10,
    maxQuantity: 2000,
    speed: "1,000 / Day",
    guarantee: "Custom Text",
  },
  {
    id: "ig-viw-story",
    japServiceId: 8170,
    category: "Instagram",
    name: "Instagram Story Views & Impressions [All Active Stories]",
    description: "View all active stories and increase reach impressions.",
    wholesaleCostUSD: 0.08,
    retailPriceNGN: 650,
    minQuantity: 100,
    maxQuantity: 50000,
    speed: "50,000 / Day",
    guarantee: "100% Reach",
  },
  {
    id: "ig-sav-shares",
    japServiceId: 8180,
    category: "Instagram",
    name: "Instagram Saves & Shares [Algorithm Explore Pusher]",
    description: "Post saves and DM shares to trigger the explore page.",
    wholesaleCostUSD: 0.10,
    retailPriceNGN: 750,
    minQuantity: 100,
    maxQuantity: 100000,
    speed: "20,000 / Day",
    guarantee: "Explore Boost",
  },

  // --- TikTok ---
  {
    id: "tt-fol-instant",
    japServiceId: 7510,
    category: "TikTok",
    name: "TikTok Followers [Instant Start | 30 Days Auto-Refill | Real Profiles]",
    description: "High quality TikTok followers to unlock live streaming & creator rewards.",
    wholesaleCostUSD: 0.25,
    retailPriceNGN: 4200,
    minQuantity: 100,
    maxQuantity: 100000,
    speed: "30,000 / Day",
    guarantee: "30 Days Refill",
  },
  {
    id: "tt-fol-nigerian",
    japServiceId: 7520,
    category: "TikTok",
    name: "TikTok Nigerian / African Followers [Real Organic Profiles]",
    description: "Real targeted African accounts to build authentic local presence.",
    wholesaleCostUSD: 0.80,
    retailPriceNGN: 7200,
    minQuantity: 50,
    maxQuantity: 20000,
    speed: "3,000 / Day",
    guarantee: "100% Organic",
  },
  {
    id: "tt-lik-real",
    japServiceId: 7433,
    category: "TikTok",
    name: "TikTok Video Likes [Real Profile Engagements]",
    description: "Instant start likes on any TikTok video.",
    wholesaleCostUSD: 0.12,
    retailPriceNGN: 950,
    minQuantity: 50,
    maxQuantity: 50000,
    speed: "10,000 / Day",
    guarantee: "Instant",
  },
  {
    id: "tt-viw-viral",
    japServiceId: 7421,
    category: "TikTok",
    name: "TikTok Viral FYP Video Views [Algorithmic For-You-Page Pusher]",
    description: "Ultra-fast views to push videos into trending feeds.",
    wholesaleCostUSD: 0.02,
    retailPriceNGN: 320,
    minQuantity: 1000,
    maxQuantity: 10000000,
    speed: "500,000 / Day",
    guarantee: "Ultra Fast",
  },
  {
    id: "tt-shr-bookmarks",
    japServiceId: 7440,
    category: "TikTok",
    name: "TikTok Video Shares & Bookmarks [Algorithm Virality Booster]",
    description: "High-retention shares and favorites that algorithm rewards.",
    wholesaleCostUSD: 0.08,
    retailPriceNGN: 750,
    minQuantity: 100,
    maxQuantity: 100000,
    speed: "20,000 / Day",
    guarantee: "High Retention",
  },
  {
    id: "tt-viw-live",
    japServiceId: 7450,
    category: "TikTok",
    name: "TikTok Live Stream Viewers [Instant 60 Mins High Retention]",
    description: "Keep your TikTok live stream viewer count boosted for 60 minutes.",
    wholesaleCostUSD: 0.60,
    retailPriceNGN: 3800,
    minQuantity: 50,
    maxQuantity: 5000,
    speed: "Instant",
    guarantee: "Live Viewers",
  },
  {
    id: "tt-com-custom",
    japServiceId: 7460,
    category: "TikTok",
    name: "TikTok Custom Comments [Targeted Active Profiles]",
    description: "Custom written positive comments for your videos.",
    wholesaleCostUSD: 0.80,
    retailPriceNGN: 6200,
    minQuantity: 10,
    maxQuantity: 2000,
    speed: "1,000 / Day",
    guarantee: "Custom Text",
  },

  // --- Twitter / X ---
  {
    id: "tw-fol-hq",
    japServiceId: 9011,
    category: "Twitter",
    name: "Twitter / X Followers [High Quality Real Profiles | 30-Day Refill Guaranteed]",
    description: "High quality real profile followers with 30 days refill guarantee.",
    wholesaleCostUSD: 0.60,
    retailPriceNGN: 7500,
    minQuantity: 50,
    maxQuantity: 25000,
    speed: "2,500 / Day",
    guarantee: "30 Days Refill",
  },
  {
    id: "tw-fol-fast",
    japServiceId: 9012,
    category: "Twitter",
    name: "Twitter / X Fast Followers [Starter Pack | Non-Drop]",
    description: "Fast start followers to boost your profile numbers quickly.",
    wholesaleCostUSD: 0.30,
    retailPriceNGN: 4200,
    minQuantity: 100,
    maxQuantity: 10000,
    speed: "5,000 / Day",
    guarantee: "Non-Drop",
  },
  {
    id: "tw-lik-hq",
    japServiceId: 8940,
    category: "Twitter",
    name: "Twitter / X Likes & Favorites [Instant High Quality Non-Drop]",
    description: "Instant engagement likes to boost tweet visibility and virality.",
    wholesaleCostUSD: 0.20,
    retailPriceNGN: 1900,
    minQuantity: 50,
    maxQuantity: 20000,
    speed: "10,000 / Day",
    guarantee: "Non-Drop",
  },
  {
    id: "tw-rt-reposts",
    japServiceId: 8945,
    category: "Twitter",
    name: "Twitter / X Retweets & Reposts [Trending Algorithm Push]",
    description: "Fast retweets to trigger algorithmic trending.",
    wholesaleCostUSD: 0.25,
    retailPriceNGN: 2500,
    minQuantity: 50,
    maxQuantity: 10000,
    speed: "5,000 / Day",
    guarantee: "Trending Push",
  },
  {
    id: "tw-imp-visits",
    japServiceId: 8950,
    category: "Twitter",
    name: "Twitter / X Impressions & Profile Visits [Monetization Ready]",
    description: "Reach impressions and profile clicks to hit X ad revenue sharing criteria.",
    wholesaleCostUSD: 0.05,
    retailPriceNGN: 650,
    minQuantity: 500,
    maxQuantity: 500000,
    speed: "100,000 / Day",
    guarantee: "Monetization Ready",
  },
  {
    id: "tw-pol-votes",
    japServiceId: 8960,
    category: "Twitter",
    name: "Twitter / X Poll Votes [Custom Choice Option]",
    description: "Vote on your chosen poll option with instant delivery.",
    wholesaleCostUSD: 0.35,
    retailPriceNGN: 3200,
    minQuantity: 100,
    maxQuantity: 25000,
    speed: "10,000 / Day",
    guarantee: "Instant Votes",
  },

  // --- Telegram ---
  {
    id: "tg-mem-lifetime",
    japServiceId: 6205,
    category: "Telegram",
    name: "Telegram Channel & Group Members [Zero Drop | 365 Days Lifetime Guarantee]",
    description: "Zero drop lifetime guaranteed members for public and private channels.",
    wholesaleCostUSD: 0.40,
    retailPriceNGN: 3900,
    minQuantity: 100,
    maxQuantity: 50000,
    speed: "20,000 / Day",
    guarantee: "Lifetime Refill",
  },
  {
    id: "tg-mem-nigerian",
    japServiceId: 6208,
    category: "Telegram",
    name: "Telegram Real Nigerian Targeted Members [Crypto & Forex Active]",
    description: "Real active Nigerian profiles interested in finance, trading and lifestyle.",
    wholesaleCostUSD: 0.90,
    retailPriceNGN: 6800,
    minQuantity: 50,
    maxQuantity: 15000,
    speed: "3,000 / Day",
    guarantee: "100% Naija Active",
  },
  {
    id: "tg-viw-posts",
    japServiceId: 6210,
    category: "Telegram",
    name: "Telegram Post Views [Instant Delivery across Recent Posts]",
    description: "Instant post views distributed across your channel's recent posts.",
    wholesaleCostUSD: 0.03,
    retailPriceNGN: 350,
    minQuantity: 200,
    maxQuantity: 100000,
    speed: "100,000 / Day",
    guarantee: "Instant",
  },
  {
    id: "tg-rea-positive",
    japServiceId: 6215,
    category: "Telegram",
    name: "Telegram Post Reactions [Positive Fire / Heart / Thumbs Up]",
    description: "Positive emojis on channel updates to increase user engagement.",
    wholesaleCostUSD: 0.06,
    retailPriceNGN: 550,
    minQuantity: 50,
    maxQuantity: 20000,
    speed: "10,000 / Day",
    guarantee: "Positive Emojis",
  },

  // --- YouTube ---
  {
    id: "yt-sub-safe",
    japServiceId: 5120,
    category: "YouTube",
    name: "YouTube Subscribers [100% Non-Drop | Channel Monetization Safe Guaranteed]",
    description: "Real YouTube subscribers safe for channel monetization and YPP approval.",
    wholesaleCostUSD: 1.80,
    retailPriceNGN: 9800,
    minQuantity: 50,
    maxQuantity: 5000,
    speed: "200 / Day",
    guarantee: "Monetization Safe",
  },
  {
    id: "yt-viw-retention",
    japServiceId: 5188,
    category: "YouTube",
    name: "YouTube High Retention Views [3-5 Mins Watch Time | Ranking Booster]",
    description: "Long watch-time views that build YouTube search ranking authority.",
    wholesaleCostUSD: 0.60,
    retailPriceNGN: 3400,
    minQuantity: 500,
    maxQuantity: 100000,
    speed: "5,000 / Day",
    guarantee: "High Watch Time",
  },
  {
    id: "yt-lik-nondrop",
    japServiceId: 5201,
    category: "YouTube",
    name: "YouTube Video Likes [Permanent High Quality Non-Drop]",
    description: "Permanent video likes from active YouTube accounts.",
    wholesaleCostUSD: 0.25,
    retailPriceNGN: 1900,
    minQuantity: 50,
    maxQuantity: 15000,
    speed: "2,000 / Day",
    guarantee: "Lifetime",
  },
  {
    id: "yt-com-custom",
    japServiceId: 5210,
    category: "YouTube",
    name: "YouTube Custom Comments [Targeted English & Active Channels]",
    description: "High quality custom relevant comments to boost video discussion.",
    wholesaleCostUSD: 1.20,
    retailPriceNGN: 6500,
    minQuantity: 10,
    maxQuantity: 2000,
    speed: "500 / Day",
    guarantee: "Custom Text",
  },

  // --- Facebook ---
  {
    id: "fb-fol-page",
    japServiceId: 4105,
    category: "Facebook",
    name: "Facebook Page Likes & Followers [Non-Drop 60D Refill Guaranteed]",
    description: "Increase fan page followers and corporate credibility.",
    wholesaleCostUSD: 0.65,
    retailPriceNGN: 4500,
    minQuantity: 100,
    maxQuantity: 50000,
    speed: "2,000 / Day",
    guarantee: "60D Refill",
  },
  {
    id: "fb-lik-reactions",
    japServiceId: 4120,
    category: "Facebook",
    name: "Facebook Post Likes & Reactions [Instant Love / Care / Like]",
    description: "Love, Care, Wow, and thumbs up reactions on public posts.",
    wholesaleCostUSD: 0.20,
    retailPriceNGN: 1500,
    minQuantity: 50,
    maxQuantity: 20000,
    speed: "5,000 / Day",
    guarantee: "Instant",
  },
  {
    id: "fb-viw-reels",
    japServiceId: 4130,
    category: "Facebook",
    name: "Facebook Video & Reel Views [Fast Algorithm Reach Booster]",
    description: "Boost watch time and video distribution across Facebook feeds.",
    wholesaleCostUSD: 0.08,
    retailPriceNGN: 600,
    minQuantity: 500,
    maxQuantity: 500000,
    speed: "100,000 / Day",
    guarantee: "Ultra Fast",
  },
  {
    id: "fb-grp-members",
    japServiceId: 4140,
    category: "Facebook",
    name: "Facebook Group Members [Active Profiles Non-Drop]",
    description: "Grow your public or private Facebook community member count.",
    wholesaleCostUSD: 0.75,
    retailPriceNGN: 4800,
    minQuantity: 100,
    maxQuantity: 25000,
    speed: "1,000 / Day",
    guarantee: "Group Growth",
  },

  // --- Spotify ---
  {
    id: "sp-str-royalty",
    japServiceId: 3015,
    category: "Spotify",
    name: "Spotify Premium Track Streams [USA/EU Royalty Eligible | High Retention]",
    description: "High-retention premium streams eligible for royalties and chart counting.",
    wholesaleCostUSD: 0.55,
    retailPriceNGN: 3400,
    minQuantity: 1000,
    maxQuantity: 500000,
    speed: "10,000 / Day",
    guarantee: "Royalty Eligible",
  },
  {
    id: "sp-fol-artist",
    japServiceId: 3022,
    category: "Spotify",
    name: "Spotify Artist Profile Followers [Non-Drop Playlist Pitch Ready]",
    description: "Real artist followers to build profile authority and pitch playlist editors.",
    wholesaleCostUSD: 0.45,
    retailPriceNGN: 3100,
    minQuantity: 100,
    maxQuantity: 50000,
    speed: "3,000 / Day",
    guarantee: "Non-Drop",
  },
  {
    id: "sp-lis-monthly",
    japServiceId: 3030,
    category: "Spotify",
    name: "Spotify Monthly Listeners [Algorithm Radio Booster]",
    description: "Increase unique monthly listener count to trigger Discover Weekly.",
    wholesaleCostUSD: 0.60,
    retailPriceNGN: 3600,
    minQuantity: 500,
    maxQuantity: 100000,
    speed: "5,000 / Day",
    guarantee: "Radio Boost",
  },

  // --- Audiomack ---
  {
    id: "audiomack-song-streams",
    japServiceId: 3610,
    category: "Audiomack",
    name: "Audiomack Song Plays / Streams [Nigerian Top Trending Chart Booster]",
    description: "High-speed plays to trigger top trending song charts in Nigeria.",
    wholesaleCostUSD: 0.25,
    retailPriceNGN: 1950,
    minQuantity: 500,
    maxQuantity: 1000000,
    speed: "50,000 / Day",
    guarantee: "Chart Booster",
  },
  {
    id: "audiomack-artist-followers",
    japServiceId: 3620,
    category: "Audiomack",
    name: "Audiomack Artist Profile Followers & Song Re-ups",
    description: "Grow your Audiomack artist catalog followers and playlist saves.",
    wholesaleCostUSD: 0.40,
    retailPriceNGN: 2800,
    minQuantity: 100,
    maxQuantity: 50000,
    speed: "5,000 / Day",
    guarantee: "Organic",
  },

  // --- Snapchat ---
  {
    id: "snapchat-followers-public",
    japServiceId: 3210,
    category: "Snapchat",
    name: "Snapchat Public Profile Followers & Subscribers [30D Refill]",
    description: "Grow your Snapchat public profile with real looking followers.",
    wholesaleCostUSD: 0.85,
    retailPriceNGN: 4800,
    minQuantity: 50,
    maxQuantity: 15000,
    speed: "1,000 / Day",
    guarantee: "30D Refill",
  },
  {
    id: "snapchat-story-views",
    japServiceId: 3215,
    category: "Snapchat",
    name: "Snapchat Spotlight & Story Views [Viral Booster]",
    description: "Fast story views to maximize spotlight virality and reach.",
    wholesaleCostUSD: 0.12,
    retailPriceNGN: 950,
    minQuantity: 500,
    maxQuantity: 100000,
    speed: "50,000 / Day",
    guarantee: "Ultra Fast",
  },

  // --- Meta Threads ---
  {
    id: "threads-followers-instant",
    japServiceId: 3310,
    category: "Threads",
    name: "Meta Threads Followers [Instant Non-Drop Accounts]",
    description: "Fast followers to build your Meta Threads account audience.",
    wholesaleCostUSD: 0.55,
    retailPriceNGN: 3800,
    minQuantity: 100,
    maxQuantity: 50000,
    speed: "10,000 / Day",
    guarantee: "Non-Drop",
  },
  {
    id: "threads-likes-reposts",
    japServiceId: 3320,
    category: "Threads",
    name: "Meta Threads Post Likes & Algorithmic Reposts",
    description: "Instant engagement on Threads conversations and updates.",
    wholesaleCostUSD: 0.18,
    retailPriceNGN: 1400,
    minQuantity: 50,
    maxQuantity: 20000,
    speed: "5,000 / Day",
    guarantee: "Instant",
  },

  // --- Discord ---
  {
    id: "discord-members-online",
    japServiceId: 3410,
    category: "Discord",
    name: "Discord Server Members [Online Active / Green Status Profiles]",
    description: "Realistic online members with active gaming / profile avatars.",
    wholesaleCostUSD: 0.70,
    retailPriceNGN: 4200,
    minQuantity: 100,
    maxQuantity: 10000,
    speed: "2,000 / Day",
    guarantee: "Online Status",
  },
  {
    id: "discord-members-offline",
    japServiceId: 3415,
    category: "Discord",
    name: "Discord Server Members [Offline Non-Drop Community Booster]",
    description: "Cost-effective server member count booster for communities.",
    wholesaleCostUSD: 0.30,
    retailPriceNGN: 2600,
    minQuantity: 100,
    maxQuantity: 25000,
    speed: "5,000 / Day",
    guarantee: "Budget Friendly",
  },

  // --- LinkedIn ---
  {
    id: "linkedin-company-followers",
    japServiceId: 3510,
    category: "LinkedIn",
    name: "LinkedIn Company Page & Professional Followers",
    description: "Corporate-grade professional followers with business profiles.",
    wholesaleCostUSD: 1.60,
    retailPriceNGN: 8500,
    minQuantity: 50,
    maxQuantity: 10000,
    speed: "500 / Day",
    guarantee: "Corporate Grade",
  },
  {
    id: "linkedin-post-likes",
    japServiceId: 3520,
    category: "LinkedIn",
    name: "LinkedIn Post Likes & Thought Leadership Reactions",
    description: "Boost career and company announcement reach on the feed.",
    wholesaleCostUSD: 0.50,
    retailPriceNGN: 3200,
    minQuantity: 50,
    maxQuantity: 5000,
    speed: "1,000 / Day",
    guarantee: "Fast Delivery",
  },

  // --- Twitch ---
  {
    id: "twitch-channel-followers",
    japServiceId: 3710,
    category: "Twitch",
    name: "Twitch Channel Followers [Affiliate Status Safe]",
    description: "Instant followers to help unlock Twitch affiliate status.",
    wholesaleCostUSD: 0.50,
    retailPriceNGN: 3200,
    minQuantity: 50,
    maxQuantity: 20000,
    speed: "5,000 / Day",
    guarantee: "Affiliate Safe",
  },
  {
    id: "twitch-live-stream-viewers",
    japServiceId: 3720,
    category: "Twitch",
    name: "Twitch Live Stream Viewers [60 Mins High Retention]",
    description: "Push your stream into the recommended top category ranks.",
    wholesaleCostUSD: 0.70,
    retailPriceNGN: 3900,
    minQuantity: 50,
    maxQuantity: 5000,
    speed: "Instant",
    guarantee: "Live Viewers",
  },

  // --- Kick ---
  {
    id: "kick-channel-followers",
    japServiceId: 3810,
    category: "Kick",
    name: "Kick.com Channel Followers [Instant Start Non-Drop]",
    description: "Grow your Kick gaming stream channel followers fast.",
    wholesaleCostUSD: 0.65,
    retailPriceNGN: 3600,
    minQuantity: 50,
    maxQuantity: 15000,
    speed: "3,000 / Day",
    guarantee: "Instant Start",
  },
  {
    id: "kick-live-stream-viewers",
    japServiceId: 3820,
    category: "Kick",
    name: "Kick.com Live Stream Viewers [60 Mins Stable Homepage Booster]",
    description: "Real-time viewer boost to land on the Kick homepage browse tab.",
    wholesaleCostUSD: 0.85,
    retailPriceNGN: 4500,
    minQuantity: 50,
    maxQuantity: 2000,
    speed: "Instant",
    guarantee: "Live Viewers",
  },

  // --- Pinterest ---
  {
    id: "pinterest-followers",
    japServiceId: 3910,
    category: "Pinterest",
    name: "Pinterest Board & Profile Followers [Active Lifestyle Pins]",
    description: "Organic-paced followers to increase brand presence.",
    wholesaleCostUSD: 0.50,
    retailPriceNGN: 3400,
    minQuantity: 100,
    maxQuantity: 20000,
    speed: "2,000 / Day",
    guarantee: "Non-Drop",
  },
  {
    id: "pinterest-repins-saves",
    japServiceId: 3920,
    category: "Pinterest",
    name: "Pinterest Pin Saves & Repins [Referral Traffic Multiplier]",
    description: "Drive referral traffic by multiplying pin saves across boards.",
    wholesaleCostUSD: 0.25,
    retailPriceNGN: 1600,
    minQuantity: 100,
    maxQuantity: 25000,
    speed: "5,000 / Day",
    guarantee: "Traffic Boost",
  },

  // --- Legacy Fallback Aliases (Backward Compatibility) ---
  {
    id: "ig-fol-1",
    japServiceId: 2830,
    category: "Instagram",
    name: "Instagram Followers [Super Fast 50k/Day | 90 Days Auto-Refill]",
    description: "Alias for ig-fol-fast",
    wholesaleCostUSD: 0.25,
    retailPriceNGN: 3850,
    minQuantity: 100,
    maxQuantity: 500000,
    speed: "50k/Day",
    guarantee: "90 Days Refill",
  },
  {
    id: "ig-fol-2",
    japServiceId: 10214,
    category: "Instagram",
    name: "Instagram Real Nigerian Followers [Organic Active Accounts]",
    description: "Alias for ig-fol-nigerian",
    wholesaleCostUSD: 0.75,
    retailPriceNGN: 6800,
    minQuantity: 50,
    maxQuantity: 20000,
    speed: "5k/Day",
    guarantee: "100% Organic",
  },
  {
    id: "ig-lik-1",
    japServiceId: 2831,
    category: "Instagram",
    name: "Instagram HQ Likes [Non-Drop + Real Looking Impressions]",
    description: "Alias for ig-lik-hq",
    wholesaleCostUSD: 0.08,
    retailPriceNGN: 550,
    minQuantity: 50,
    maxQuantity: 100000,
    speed: "100k/Day",
    guarantee: "Instant 0-5m",
  },
  {
    id: "ig-viw-1",
    japServiceId: 8155,
    category: "Instagram",
    name: "Instagram Reel & Video Views [Algorithm Booster]",
    description: "Alias for ig-viw-reels",
    wholesaleCostUSD: 0.03,
    retailPriceNGN: 350,
    minQuantity: 500,
    maxQuantity: 1000000,
    speed: "500k/Day",
    guarantee: "Ultra Fast",
  },
  {
    id: "ig-com-1",
    japServiceId: 8190,
    category: "Instagram",
    name: "Instagram Custom Comments [Targeted Active Profiles]",
    description: "Alias for ig-com-custom",
    wholesaleCostUSD: 0.75,
    retailPriceNGN: 5800,
    minQuantity: 10,
    maxQuantity: 2000,
    speed: "1k/Day",
    guarantee: "Custom Text",
  },
  {
    id: "tt-fol-1",
    japServiceId: 7510,
    category: "TikTok",
    name: "TikTok Followers [Global Active | 30 Days Auto-Refill]",
    description: "Alias for tt-fol-instant",
    wholesaleCostUSD: 0.25,
    retailPriceNGN: 4200,
    minQuantity: 100,
    maxQuantity: 100000,
    speed: "30k/Day",
    guarantee: "Popular",
  },
  {
    id: "tt-viw-1",
    japServiceId: 7421,
    category: "TikTok",
    name: "TikTok Viral Video Views [Algorithmic For-You-Page Boost]",
    description: "Alias for tt-viw-viral",
    wholesaleCostUSD: 0.02,
    retailPriceNGN: 320,
    minQuantity: 1000,
    maxQuantity: 10000000,
    speed: "500k/Day",
    guarantee: "Ultra Fast",
  },
  {
    id: "tt-lik-1",
    japServiceId: 7433,
    category: "TikTok",
    name: "TikTok Video Likes [Real Profile Engagements]",
    description: "Alias for tt-lik-real",
    wholesaleCostUSD: 0.12,
    retailPriceNGN: 950,
    minQuantity: 50,
    maxQuantity: 50000,
    speed: "10k/Day",
    guarantee: "Instant",
  },
  {
    id: "tt-shr-1",
    japServiceId: 7440,
    category: "TikTok",
    name: "TikTok Video Shares & Bookmarks [Algorithm Trigger]",
    description: "Alias for tt-shr-bookmarks",
    wholesaleCostUSD: 0.08,
    retailPriceNGN: 750,
    minQuantity: 100,
    maxQuantity: 100000,
    speed: "20k/Day",
    guarantee: "High Retention",
  },
  {
    id: "tg-mem-1",
    japServiceId: 6205,
    category: "Telegram",
    name: "Telegram Channel / Group Members [Zero Drop | Lifetime Guarantee]",
    description: "Alias for tg-mem-lifetime",
    wholesaleCostUSD: 0.40,
    retailPriceNGN: 3900,
    minQuantity: 100,
    maxQuantity: 50000,
    speed: "20k/Day",
    guarantee: "Lifetime Refill",
  },
  {
    id: "tg-viw-1",
    japServiceId: 6210,
    category: "Telegram",
    name: "Telegram Post Views [Instant Multi-Post Distribution]",
    description: "Alias for tg-viw-posts",
    wholesaleCostUSD: 0.03,
    retailPriceNGN: 350,
    minQuantity: 200,
    maxQuantity: 100000,
    speed: "100k/Day",
    guarantee: "Instant",
  },
  {
    id: "tg-rea-1",
    japServiceId: 6215,
    category: "Telegram",
    name: "Telegram Post Reactions [Positive Fire / Heart / Thumbs Up]",
    description: "Alias for tg-rea-positive",
    wholesaleCostUSD: 0.06,
    retailPriceNGN: 550,
    minQuantity: 50,
    maxQuantity: 20000,
    speed: "10k/Day",
    guarantee: "Fast",
  },
  {
    id: "tw-fol-1",
    japServiceId: 9011,
    category: "Twitter",
    name: "Twitter / X Followers [7-Day Refill Guaranteed]",
    description: "Alias for tw-fol-hq",
    wholesaleCostUSD: 0.60,
    retailPriceNGN: 7500,
    minQuantity: 50,
    maxQuantity: 25000,
    speed: "2.5k/Day",
    guarantee: "Best Seller",
  },
  {
    id: "tw-lik-1",
    japServiceId: 8940,
    category: "Twitter",
    name: "Twitter / X Likes [Instant High Quality]",
    description: "Alias for tw-lik-hq",
    wholesaleCostUSD: 0.20,
    retailPriceNGN: 1900,
    minQuantity: 50,
    maxQuantity: 20000,
    speed: "10k/Day",
    guarantee: "Non-Drop",
  },
  {
    id: "tw-rt-1",
    japServiceId: 8945,
    category: "Twitter",
    name: "Twitter / X Retweets & Reposts [Trending Push]",
    description: "Alias for tw-rt-reposts",
    wholesaleCostUSD: 0.25,
    retailPriceNGN: 2500,
    minQuantity: 50,
    maxQuantity: 10000,
    speed: "5k/Day",
    guarantee: "Fast",
  },
  {
    id: "tw-imp-1",
    japServiceId: 8950,
    category: "Twitter",
    name: "Twitter / X Impressions & Profile Visits",
    description: "Alias for tw-imp-visits",
    wholesaleCostUSD: 0.05,
    retailPriceNGN: 650,
    minQuantity: 500,
    maxQuantity: 500000,
    speed: "100k/Day",
    guarantee: "Ultra Fast",
  },
  {
    id: "yt-sub-1",
    japServiceId: 5120,
    category: "YouTube",
    name: "YouTube Subscribers [Non-Drop | Channel Monetization Safe]",
    description: "Alias for yt-sub-safe",
    wholesaleCostUSD: 1.80,
    retailPriceNGN: 9800,
    minQuantity: 50,
    maxQuantity: 5000,
    speed: "200/Day",
    guarantee: "Monetization Safe",
  },
  {
    id: "yt-viw-1",
    japServiceId: 5188,
    category: "YouTube",
    name: "YouTube High Retention Views [3-5 Mins Watch Time]",
    description: "Alias for yt-viw-retention",
    wholesaleCostUSD: 0.60,
    retailPriceNGN: 3400,
    minQuantity: 500,
    maxQuantity: 100000,
    speed: "5k/Day",
    guarantee: "High Watch Time",
  },
  {
    id: "yt-lik-1",
    japServiceId: 5201,
    category: "YouTube",
    name: "YouTube Video Likes [Instant High Quality Non-Drop]",
    description: "Alias for yt-lik-nondrop",
    wholesaleCostUSD: 0.25,
    retailPriceNGN: 1900,
    minQuantity: 50,
    maxQuantity: 15000,
    speed: "2k/Day",
    guarantee: "Lifetime",
  },
  {
    id: "fb-fol-1",
    japServiceId: 4105,
    category: "Facebook",
    name: "Facebook Page Likes & Followers [Non-Drop 30D Refill]",
    description: "Alias for fb-fol-page",
    wholesaleCostUSD: 0.65,
    retailPriceNGN: 4500,
    minQuantity: 100,
    maxQuantity: 50000,
    speed: "2k/Day",
    guarantee: "30D Refill",
  },
  {
    id: "fb-lik-1",
    japServiceId: 4120,
    category: "Facebook",
    name: "Facebook Post Reactions & Likes [Instant Love/Care/Like]",
    description: "Alias for fb-lik-reactions",
    wholesaleCostUSD: 0.20,
    retailPriceNGN: 1500,
    minQuantity: 50,
    maxQuantity: 20000,
    speed: "5k/Day",
    guarantee: "Instant",
  },
  {
    id: "fb-viw-1",
    japServiceId: 4130,
    category: "Facebook",
    name: "Facebook Video & Reel Views [Fast Reach Boost]",
    description: "Alias for fb-viw-reels",
    wholesaleCostUSD: 0.08,
    retailPriceNGN: 600,
    minQuantity: 500,
    maxQuantity: 500000,
    speed: "100k/Day",
    guarantee: "Ultra Fast",
  },
  {
    id: "sp-str-1",
    japServiceId: 3015,
    category: "Spotify",
    name: "Spotify Premium Track Streams [USA/EU Royalty Eligible]",
    description: "Alias for sp-str-royalty",
    wholesaleCostUSD: 0.55,
    retailPriceNGN: 3400,
    minQuantity: 1000,
    maxQuantity: 500000,
    speed: "10k/Day",
    guarantee: "Royalty Eligible",
  },
  {
    id: "sp-fol-1",
    japServiceId: 3022,
    category: "Spotify",
    name: "Spotify Artist Profile Followers [Non-Drop Authority]",
    description: "Alias for sp-fol-artist",
    wholesaleCostUSD: 0.45,
    retailPriceNGN: 3100,
    minQuantity: 100,
    maxQuantity: 50000,
    speed: "3k/Day",
    guarantee: "Non-Drop",
  },
];

export class JapService {
  private static apiKey = process.env.JAP_API_KEY || "";

  private static async post<T>(params: Record<string, string | number>): Promise<T> {
    if (!this.apiKey) {
      throw new Error("JAP_API_KEY is not configured in environment variables.");
    }

    const body = new URLSearchParams({
      key: this.apiKey,
      ...Object.fromEntries(Object.entries(params).map(([k, v]) => [k, String(v)])),
    });

    const response = await fetch(JAP_API_URL, {
      method: "POST",
      headers: {
        "Content-Type": "application/x-www-form-urlencoded",
      },
      body: body.toString(),
    });

    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(`JAP API Error (${response.status}): ${errorText}`);
    }

    return response.json() as Promise<T>;
  }

  /**
   * Check wholesale float balance on JAP
   */
  static async getBalance(): Promise<{ balance: number; currency: string }> {
    if (!this.apiKey) {
      return { balance: 24.8, currency: "USD" };
    }

    const data = await this.post<{ balance: string; currency: string }>({
      action: "balance",
    });

    return {
      balance: parseFloat(data.balance) || 0,
      currency: data.currency || "USD",
    };
  }

  /**
   * Create an SMM boosting order
   * @param serviceId - The JAP numeric service ID (e.g. 9011)
   * @param link - Social media profile or post URL
   * @param quantity - Number of followers, likes, or views
   */
  static async createOrder(
    serviceId: number,
    link: string,
    quantity: number
  ): Promise<{ order: number }> {
    if (!this.apiKey) {
      return { order: Math.floor(1000000 + Math.random() * 9000000) };
    }

    const data = await this.post<{ order?: number; error?: string }>({
      action: "add",
      service: serviceId,
      link,
      quantity,
    });

    if (data.error || !data.order) {
      throw new Error(`JAP API Error: ${data.error || "Order rejected by provider"}`);
    }

    return { order: Number(data.order) };
  }

  /**
   * Check progress of an order
   */
  static async getOrderStatus(orderId: number | string): Promise<{
    charge: string;
    start_count: string;
    status: "Pending" | "In progress" | "Completed" | "Partial" | "Canceled";
    remains: string;
    currency: string;
  }> {
    if (!this.apiKey) {
      return {
        charge: "0.375",
        start_count: "250",
        status: "In progress",
        remains: "150",
        currency: "USD",
      };
    }

    return this.post({
      action: "status",
      order: orderId,
    });
  }
}
